### ISSUE TITLE
[Bug]: Gajim setup fails

### ISSUE THREAD

**Issue by chris-est** [ltguillaume/schep#1]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

gajim

### Expected/Current Behaviour

Gajim is installed

### Steps to Reproduce

```console
scoop install ltguillaume_schep/gajim
```

### Possible Solution

-

### Scoop and Buckets Version

```console
latest
```

### Scoop Config

```console
-
```

### PowerShell Version

```console
-
```

### Additional Softwares

Thank you for packaging gajim :-)

The installation fails for me, because the installer file is named "gajim-portable.exe": 
https://github.com/ltguillaume/schep/blob/ee0143c12680e784d9e7b824b069f760dcf8e98a/bucket/gajim.json#L21
The downloaded file is actually named as in the url: "Gajim-Portable-1.9.3-64bit.exe"

Changing the line to the correct filename fixes the installation for me.

**Comment by ltguillaume** [comment]
That's a good catch! Should be fixed now, could you try this again?

**Comment by chris-est** [comment]
Hello, sorry for the delay. I uninstalled gajim and re-installed with your changes, this works for me now 🥳

**Comment by ltguillaume** [comment]
Great! Thanks for reporting back, I'll close the issue 👍
